#!/bin/sh

# Configuration files
[ -f /etc/conf.d/houyi ] && . /etc/conf.d/houyi
[ -f /etc/houyi ] && . /etc/houyi

detect_backlight() {
	for item in "$backlight_base"/*; do
		local backlight_dir=$(readlink -e "$item")
		[ -f "$backlight_dir"/brightness -a -f "$backlight_dir"/max_brightness ] \
			&& echo "$backlight_dir"
	done | head -1
}

set_brightness() {
	local brightness="$1"
	[ "$brightness" -lt 0 ] && brightness=1
	[ "$brightness" -gt "$max_brightness" ] && brightness="$max_brightness"
	echo "$brightness" | tee "$backlight"/brightness
}

backlight_base="${BACKLIGHT_BASE:-/sys/class/backlight}"
backlight="${BACKLIGHT:-$(detect_backlight)}"
backlight_steps="${BACKLIGHT_STEPS:-10}"

max_brightness=$(cat "$backlight"/max_brightness)
brightness=$(cat "$backlight"/brightness)
brightness_interval=$(($max_brightness / $backlight_steps))

case "$1" in
	+)
		set_brightness $(($brightness + $brightness_interval))
		;;
	++)
		set_brightness "$max_brightness"
		;;
	-)
		set_brightness $(($brightness - $brightness_interval))
		;;
	--)
		set_brightness 1
		;;
	-.)
		set_brightness "$brightness_interval"
		;;
	0)
		set_brightness 0
		;;
	-h)
		cat <<-EOF
Usage: $(basename "$0") [-h] OP

Operators:
 +   Increase brightness one step
 ++  Set brightness to maximum
 -   Decrease brightness one step
 --  Set brightness to minimum non-zero (1)
 -.  Set brightness to one step above zero
 0   Set brightness to zero

Any other value will set the brightness directly.

Providing no operator will display the current and maximum brightness.

The backlight to modify can be set via the BACKLIGHT environment variable. If
unset, the BACKLIGHT_BASE directory (default: /sys/class/backlight) will be
searched for directories containing 'brightness' and 'max_brightness' files.

Step size is the maximum brightness divided by BACKLIGHT_STEPS (default: 10).

Configuration is read by sourcing /etc/conf.d/houyi and /etc/houyi, in that
order, if the files exist.

		EOF
		;;
	-V)
		echo "$(basename "$0")-1"
		;;
	*)
		if [ -z "$1" ]; then
			echo "$brightness/$max_brightness"
		else
			echo "$1" | tee "$backlight"/brightness
		fi
		;;
esac
